# Generated by Django 5.1.5 on 2025-02-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_category_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickethistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('feedback', 'Feedback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket'),
        ),
    ]
